export const soups = {
  soups: [
    {
      itemID: 1,
      name: "Nápolyi paradicsomleves",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 2,
      name: "Minestrone zöldségleves",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 3,
      name: "Szezonális leves",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 4,
      name: "Savanyú-erős leves",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 5,
      name: "Bajor májgombócleves",
      ingredients: "todo",
      price: "todo",
    },
  ],
};

export const gyros = {
  gyros: [
    {
      itemID: 6,
      name: "Csirkés gyros pitában",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 7,
      name: "Görög saláta pitában ",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 8,
      name: "Vega pita",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 9,
      name: "Szultán tál",
      ingredients: "todo",
      price: "todo",
    },
  ],
};

export const salads = {
  salads: {
    bowls: [
      {
        itemID: 10,
        name: "Bruschetta",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 11,
        name: "Görög",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 12,
        name: "Mediterrán falatok",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 13,
        name: "Caprese",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 14,
        name: "Szicíliai",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 15,
        name: "Grande verdura",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 16,
        name: "Rucola verdura",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 17,
        name: "Caesar",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 18,
        name: "Bonita saláta",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 19,
        name: "Görög-csirke tál",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 20,
        name: "Bufala Caprese D.O.P. tál",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 21,
        name: "Nizzai",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 22,
        name: "Made in Italy tál",
        ingredients: "todo",
        price: "todo",
      },
    ],
    extra: [
      {
        itemID: 23,
        name: "Házi készítésű kiscipó",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 24,
        name: "Focaccia",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 25,
        name: "Grissini",
        ingredients: "todo",
        price: "todo",
      },
    ],
  },
};

export const pizzas = {
  pizzas: {
    electricOven: [
      {
        itemID: 26,
        name: "Focaccia",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 27,
        name: "Pizza Marinara",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 28,
        name: "Grissini",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 29,
        name: "Margherita",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 30,
        name: "Gombás",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 31,
        name: "Sonkás",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 32,
        name: "Modena",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 33,
        name: "Hawai",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 34,
        name: "Ökörszem",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 35,
        name: "Vega",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 36,
        name: "Mexikói",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 37,
        name: "Verdura",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 38,
        name: "Tarjás",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 39,
        name: "Húsos",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 40,
        name: "Sonkás-gombás",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 41,
        name: "Ham and eggs",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 42,
        name: "Piedone",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 43,
        name: "Mustáros tarjás",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 44,
        name: "Bajor",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 45,
        name: "Baconos",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 46,
        name: "Szicíliai",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 47,
        name: "Chilis",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 48,
        name: "Csabai csípős",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 49,
        name: "Inyenc",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 50,
        name: "Pizza Bufala",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 51,
        name: "Pepperoni",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 52,
        name: "Salami Milano",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 53,
        name: "Pizza Napoli",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 54,
        name: "Quattro formaggi",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 55,
        name: "Szultán kedvence",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 56,
        name: "Gyros",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 57,
        name: "Mustáros csirkés",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 58,
        name: "Tanyasi",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 59,
        name: "Pizza Calabria",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 60,
        name: "Tonhalas",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 61,
        name: "Hústorony",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 62,
        name: "Quattro stagioni",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 63,
        name: "Feketeerdei pizza",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 64,
        name: "Mascarpone",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 65,
        name: "Pármai sonkás",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 66,
        name: "Frutti di Mare",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 67,
        name: "Pizza Bonita",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 68,
        name: "Made in Italy Pizza",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 69,
        name: "Pizza Latina",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 70,
        name: "Pizza, ahogy ön szereti",
        ingredients: "todo",
        price: "todo",
      },
    ],
    stoneOven: [
      {
        itemID: 71,
        name: "Focaccia",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 72,
        name: "Focaccia Rossa",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 73,
        name: "Marinara",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 74,
        name: "Margherita",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 75,
        name: "Al filetto",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 76,
        name: "Bufalina D.O.P",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 77,
        name: "Pizza Vegetariano",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 78,
        name: "Quattro formaggi",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 79,
        name: "Proscutto cotto",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 80,
        name: "Pancetta",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 81,
        name: "Salami Milano",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 82,
        name: "Diavola",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 83,
        name: "Sárga pizza",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 84,
        name: "Zöld pestos pizza",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 85,
        name: "Tonno Napoletana",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 86,
        name: "Napoli - Békéscsaba",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 87,
        name: "Pizza Italiano",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 89,
        name: "Nduja Calabrese D.O.P",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 90,
        name: "Sárga pizza pancettával",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 91,
        name: "Proscutto Crudo",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 92,
        name: "Nápolyi Calzone nutellával és mascarponéval töltve",
        ingredients: "todo",
        price: "todo",
      },
    ],
  },
};

export const pastas = {
  pastas: {
    normal: [
      {
        itemID: 93,
        name: "Spaghetti aglio, olio e pepperoncini",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 94,
        name: "Spaghetti Napoletana",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 95,
        name: "Penne all'Arrabbiata",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 96,
        name: "Rozé penne",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 97,
        name: "Vegetáriánus",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 98,
        name: "Penne contadinal",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 99,
        name: "Spaghetti carbonara",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 100,
        name: "Csabai ízek",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 101,
        name: "Pasta brokkoli",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 102,
        name: "Mascarponés farfalle vagy fusili",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 104,
        name: "Spenótos fusili",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 105,
        name: "Szultán tésztája",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 106,
        name: "Alfredo penne",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 107,
        name: "Török penne",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 108,
        name: "Penne Toscana",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 109,
        name: "Bolognai spaghetti",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 110,
        name: "Spaghetti frutti de mare",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 111,
        name: "Lazacos farfalle",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 112,
        name: "Tészta mediterrán fekete kagylóval",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 113,
        name: "Garnélás spaghetti",
        ingredients: "todo",
        price: "todo",
      },
    ],
    puglia: [
      {
        itemID: 114,
        name: "Pasta Genovese",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 115,
        name: "Papfojtó",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 116,
        name: "Antonio tésztája",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 117,
        name: "Bufala mozzarellás tészta - napi tészta kínálattal",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 118,
        name: "Bonita tészta",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 119,
        name: "Pasta Napoli",
        ingredients: "todo",
        price: "todo",
      },
    ],
    homeMade: [
      {
        itemID: 120,
        name: "Scialatielli",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 121,
        name: "Gnocchi 3 colori",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 122,
        name: "Gnocchi 4 formaggi",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 123,
        name: "Tonhalas tagliatelle",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 124,
        name: "Tagliatelle Italia",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 125,
        name: "Aranyló házi készítésű erdei gombás pappardelle",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 126,
        name: "Ravioli spenót",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 127,
        name: "Zöld ravioli gorgonzolával",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 128,
        name: "Gnocchi pirított sonkával",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 129,
        name: "Vajas Garnélás Scialatielli",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 130,
        name: "Nduja Scialatielli D.O.P",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 131,
        name: "Kacsa ragus Scialatielli",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 132,
        name: "Vongole és Nduja",
        ingredients: "todo",
        price: "todo",
      },
    ],
    parmesan: [
      {
        itemID: 132,
        name: "Észak-Olasz speck sonkával, cukkinivel,",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 132,
        name: "Gnocchi házi tészta tejszínes rukkolával, csirkehúsokkal",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 132,
        name: "Scialatielli paradicsomos marharaguval,",
        ingredients: "todo",
        price: "todo",
      },
      {
        itemID: 132,
        name: "Pasta della Nonna: sodort házi tészta,",
        ingredients: "todo",
        price: "todo",
      },
    ],
  },
};

export const grill = {
  grill: [
    {
      itemID: 133,
      name: "Grill padlizsán",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 134,
      name: "Csirkesteak",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 135,
      name: "Fűszeres karaj steak",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 136,
      name: "Fűszeres karaj steak",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 137,
      name: "Pokoli pecsenye",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 138,
      name: "Grillezett füstölt sajt",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 139,
      name: "Pulykasteak",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 140,
      name: "Szecsuáni csirkehús",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 141,
      name: "Tengeri halszeletek",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 142,
      name: "Hússzeletek marhából",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 143,
      name: "Marha steak (200g)",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 144,
      name: "Mediterrán fekete kagyló (marinara)",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 145,
      name: "Mediterrán fekete kagyló (zelleres)",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 146,
      name: "Mediterrán fekete kagyló (paradicsomos)",
      ingredients: "todo",
      price: "todo",
    },
  ],
};

export const desserts = {
  desserts: [
    {
      itemID: 147,
      name: "Creme Brulée",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 148,
      name: "Tiramisu Classic",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 149,
      name: "Panna Cotta",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 150,
      name: "Cantuccino",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 151,
      name: "Sorrento-i citromtorta",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 152,
      name: "Házi sajtkrémtorta",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 153,
      name: "Zuppa Inglese",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 154,
      name: "Zuppa Inglese di Roma",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 155,
      name: "Narancsos csokoládétorta",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 156,
      name: "Nápolyi Gizella tortája",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 157,
      name: "Torta di Pistacchio",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 158,
      name: "Nápolyi Calzone nutellával és mascarponéval töltve",
      ingredients: "todo",
      price: "todo",
    },
  ],
};

export const drinks = {
  drinks: [
    {
      itemID: 159,
      name: "Narancslé",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 160,
      name: "Házi limonádé",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 161,
      name: "Bonita fröccs",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 162,
      name: "Szürt viz",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 163,
      name: "Szóda",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 164,
      name: "Üdítők",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 165,
      name: "A ház borai, száraz",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 166,
      name: "Sörök",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 167,
      name: "Csapolt sör",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 168,
      name: "Limoncello citronata",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 169,
      name: "Ramasotti",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 170,
      name: "Grappa",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 180,
      name: "Aperol Spritz koktél",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 181,
      name: "Grappa",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 182,
      name: "Hugo Spritz koktél",
      ingredients: "todo",
      price: "todo",
    },
    {
      itemID: 183,
      name: "Martini Fiero koktél",
      ingredients: "todo",
      price: "todo",
    },
  ],
};
